# Generated by Django 2.0.6 on 2018-06-27 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_hour', '0003_auto_20180618_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'proxy': True,
                'indexes': [],
            },
            bases=('work_hour.registrodiario',),
        ),
        migrations.AlterField(
            model_name='atividadediaria',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_hour.Atividade', verbose_name='atividade'),
        ),
        migrations.AlterField(
            model_name='atividadediaria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_hour.Cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='atividadediaria',
            name='registro_diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_hour.RegistroDiario', verbose_name='horario'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
